language: objective-c
osx_image: xcode8.1
script:
- set -o pipefail
- xcodebuild clean build test -workspace Example/BMASpinningLabel.xcworkspace -scheme BMASpinningLabel -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7' -configuration Debug | xcpretty
- bash <(curl -s https://codecov.io/bash) -J 'BMASpinningLabel'
